[package]
name = "siamesedb"
version = "0.1.4"
authors = ["aki <aki.akaguma@hotmail.com>"]
edition = "2018"
description = "The simple local key-value store."
keywords = ["key-value", "store", "database", "embedded-database"]
categories = ["database"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aki-akaguma/siamesedb"

[[bin]]
name = "test_main"
path = "src/test_main.rs"

[[bin]]
name = "test_main2"
path = "src/test_main2.rs"

[features]
default = ["vf_vu64", "node_cache"]
#default = ["vf_vu64", "buf_lru"]

# for developping
vf_u32u32 = []
vf_u64u64 = []
vf_vu64 = []

buf_lru = []
buf_stats = []

node_cache = []

# for test
test_large_data = []

[dependencies]
rabuf = "0.1"
vu64 = "0.1"
#rabuf = { git = "https://github.com/aki-akaguma/rabuf" }
#vu64 = { git = "https://github.com/aki-akaguma/vu64" }
#rabuf = { path = "../rabuf" }
#vu64 = { path = "../vu64" }

[dev-dependencies]
#criterion = "0.3"

[workspace]
members = [
    "xtask",
]
