[package]
name = "siamesedb"
version = "0.1.1"
authors = ["aki <aki.akaguma@hotmail.com>"]
edition = "2018"
description = "The simple local key-value store."
keywords = ["key-value", "store", "database", "embedded-database"]
categories = ["database"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aki-akaguma/siamesedb"

[[bin]]
name = "test_main"
path = "src/test_main.rs"

[features]
default = ["vf_vu64"]
#default = ["vf_vu64", "buf_lru"]

# for developping
vf_u32u32 = []
vf_u64u64 = []
vf_vu64 = []

buf_lru = []
buf_stats = []

[dependencies]

[dev-dependencies]
#criterion = "0.3"

[workspace]
members = [
    "xtask",
]
