[package]
name = "shamdb"
version = "0.1.0"
authors = ["aki <aki.akaguma@hotmail.com>"]
edition = "2018"
description = "The simple local key-value store."
keywords = ["store", "database"]
categories = ["database"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aki-akaguma/shamdb"

[[bin]]
name = "test_main"
path = "src/test_main.rs"

[features]
#default = ["key_cache", "vf_u32u32"]
#default = ["key_cache", "vf_u64u64"]
default = ["key_cache", "vf_v64"]
#default = ["key_cache", "vf_vint64"]
#default = ["key_cache", "vf_leb128"]
#default = ["key_cache", "vf_sqlvli"]

# for developping
key_cache = []

vf_u32u32 = []
vf_u64u64 = []
vf_v64 = []
vf_vint64 = []
vf_leb128 = []
vf_sqlvli = []

[dependencies]
#vint64 = { version="1.0", optional=true }

[dev-dependencies]
#criterion = "0.3"

[workspace]
members = [
    "xtask",
]
