[package]
name = "shamdb"
version = "0.1.0"
authors = ["aki <aki.akaguma@hotmail.com>"]
edition = "2018"
description = "The simple local key-value store."
keywords = ["store", "database"]
categories = ["database"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aki-akaguma/shamdb"

[[bin]]
name = "test_main"
path = "src/test_main.rs"

[features]
default = ["key_cache", "dat_v64v64", "idx_v64v64"]
#default = ["dat_v64v64", "idx_v64v64"]

# for developping
key_cache = []

dat_u16u32 = []
dat_u64u64 = []
dat_v64v64 = []
dat_varvar = []

idx_u32u32 = []
idx_u64u64 = []
idx_varvar = []
idx_v64v64 = ["vint64"]
idx_vlivli = []

[dependencies]
byteorder = "1.4"
vint64 = { version="1.0", optional=true }

[dev-dependencies]
#criterion = "0.3"

[workspace]
members = [
    "xtask",
]
